### ISSUE TITLE
CommandAPI documentation doesn't say that the project is provided

### ISSUE THREAD

**Issue by Draycia** [JorelAli/CommandAPI#132]
**CommandAPI version**
4.0

**Minecraft version**
1.16.2

**Describe the bug**
Shading in CommandAPI 4.0 and loading on 1.16.2 results in an UnsupportedVersionException.
https://paste.gg/p/anonymous/bacd5530f0f64e2ab6626ccd5cac78f6

**My code**
This code reproduces the behavior:
```java
        String commandName = carbonChat.getConfig().getString("commands.switch.name", "switch");
        List<String> commandAliases = carbonChat.getConfig().getStringList("commands.switch.aliases");

        LinkedHashMap<String, Argument> setChannelArguments = new LinkedHashMap<>();
        setChannelArguments.put("channel", CarbonUtils.channelArgument());

        new CommandAPICommand(commandName)
                .withArguments(setChannelArguments)
                .withAliases(commandAliases.toArray(new String[0]))
                .withPermission(CommandPermission.fromString("carbonchat.switch"))
                .executesPlayer(this::setChannel)
                .register();
```

```groovy
    compile "dev.jorel:commandapi-core:4.0"
```

**Additional context**
It seems CommandAPIVersionHandler does not have a case for 1.16.2, despite there being modules which would handle it.

https://github.com/JorelAli/CommandAPI/blob/master/CommandAPI/commandapi-core/src/main/java/dev/jorel/commandapi/CommandAPIVersionHandler.java#L49-L56

https://github.com/JorelAli/CommandAPI/blob/master/CommandAPI/commandapi-1.16.2/src/main/java/dev/jorel/commandapi/nms/NMS_1_16_R2.java

**Comment by JorelAli** [comment]
This isn't a bug. Why are you shading the CommandAPI?
The command API doesn't load that version handler file, it instead loads the one from commandapi-extra

**Comment by Draycia** [comment]
I'd simply rather not force users to install an extra plugin if not necessary.

Is there any reasoning on why one version of the file doesn't support 1.16 but the other does?

**Comment by JorelAli** [comment]
[1] The CommandAPI _cannot_ be shaded due to the order in which it must load everything. The CommandAPI is a plugin that registers events and runs specific code at specific loading times (e.g. `onLoad()` and `onEnable()`, as well as extra code that must be run once the server has finished loading).

[2] Yes, it was for performance. The old file shouldn't really exist _(it's supposed to be empty and I must have gotten lazy and forgot to empty the file)_. The first file uses reflection to instantiate the correct version of NMS, whereas the new one doesn't and thus has better performance. The comment at the top of the first file explains all of this in detail.

**Comment by Draycia** [comment]
`clearly` is debatable since a majority of other command libraries can be shaded and your documentation for gradle usage uses `compile`.

Either way, I concede. As is it can't be shaded in.

**Comment by JorelAli** [comment]
Ah, that's a good point!
I'll make sure to include this, thanks!!

**Comment by JorelAli** [comment]
I've added the building scope to the documentation, hopefully this should make it clearer now. Thanks again!
