### ISSUE TITLE
.withRequirement predicate is not checked for command suggestions

### ISSUE THREAD

**Issue by SHsuperCM** [JorelAli/CommandAPI#159]
**CommandAPI version**
v5.2

**Minecraft version**
1.16.3

**Describe the bug**
The requirement predicate is not checked when suggesting commands

**My code**
This code reproduces the behavior:
Just debug on a new simple command and see when the predicate fires, it happens regardless of the command.

**Expected behavior**
Every time the server suggests completion for commands and arguments, requirements should be considered.

**Comment by JorelAli** [comment]
This is actually intended behavior. The way Minecraft handles requirements (and also permissions) is it checks it when permissions change for a player, or when the player joins the game. Suggestions are processed when an argument's suggestions are overridden.

This is not a flaw with the CommandAPI, this is just how Minecraft handles things and I can't change that. Sorry!

**Comment by SHsuperCM** [comment]
Huh.. that's really unintuitive on their part.. Thanks for the explanation tho!

**Comment by JorelAli** [comment]
This is described (very briefly) in the CommandAPI's documentation [here](https://www.jorel.dev/CommandAPI/5.2/requirements.html#updating-requirements). Due to how this is handled, the CommandAPI added a method `CommandAPI.updateRequirements(Player)`, which you can use to force recalculate the permissions/requirements of a player.

I hope this helps!

**Comment by SHsuperCM** [comment]
Thank you so so very much! I had no idea! I was about to scrap a feature completely haha
