### ISSUE TITLE
Command with optional/different argument fails to create permissions

### ISSUE THREAD

**Issue by toddharrison** [JorelAli/CommandAPI#184]
**CommandAPI version**
5.8

**Minecraft version**
1.16.4

**Describe the bug**
When defining multiple command registrations that provide optional or different arguments, and specifying different permission nodes for each of the commands, only the first permission is registered and the second command tails along with it.

**My code**
This code reproduces the behavior:
```java
new CommandAPICommand("kill")
    .withPermission("kill.self")
    .executesPlayer((player, args) -> {
        player.setHealth(0);
    })
    .register();

// Register our second /kill <target> command
new CommandAPICommand("kill")
    .withArguments(new PlayerArgument("target"))
    .withPermission("kill.other")
    .executesPlayer((player, args) -> {
        ((Player) args[0]).setHealth(0);
    })
    .register();
```

**Expected behavior**
Should be able to use permissions to restrict access to kill other and kill self independently.

**Additional context**
Also, using luckperms to manage permissions. When looking at the permissions it scanned, only the first permission appears, not the second one.

**Comment by JorelAli** [comment]
As odd as this may seem, this is actually working as intended. In the code example that you've provided, you've registered two commands "/kill" with two different permissions. However, since they both have the same name and both have different permissions, the CommandAPI will only register the first permission.

This is the difference between registering permissions on the command-level compared to registering permissions on the argument-level. You probably want to move the permission of the second command to the argument.

**Comment by toddharrison** [comment]
Will give this a try!

**Comment by toddharrison** [comment]
Looks good, thanks! The argument permission does not appear for luckperms (the other one does), but not sure why that would be.
