### ISSUE TITLE
When both shading commandapi and nbtapi package directory error

### ISSUE THREAD

**Issue by wnynya** [JorelAli/CommandAPI#223]
**CommandAPI version:** _6.0.5_

**Minecraft version:** _1.17_

**What I did:**
I shaded plugin both CommandAPI and NBTAPI

**Actual result:**
When building plugin this happen
`class file for de.tr7zw.nbtapi.NBTContainer not found`

**What should have happened:**
Build should be successful

It might be NBTAPI package dir change to "de.tr7zw.changeme.nbtapi.NBTContainer" but CommandAPI's import dir is not changed

**Comment by JorelAli** [comment]
The NBTAPI has two methods at which it can be used:
- It can be used as a standalone plugin, where the API .jar file is included in your plugins directory
- It can be shaded into another plugin, and its package names have to be relocated

In order to use the CommandAPI with the NBTAPI standalone plugin, the CommandAPI has to import `de.tr7zw.nbtapi.NBTContainer`. However, if the CommandAPI wants to be used with a shaded version of the NBTAPI, it has to import `de.tr7zw.changeme.nbtapi.NBTContainer` and then be relocated at compile time when both the NBTAPI and CommandAPI are shaded in together.

So effectively, the package for the NBTAPI that the CommandAPI should import depends on whether the user is shading the NBTAPI or not. I think the best way to handle such a case is for me to create a separate module, such as `commandapi-shade-nbtapi`, which uses all of the NBTAPI `de.tr7zw.changeme.nbtapi.NBTContainer` packages instead of the standalone packages.

**Comment by JorelAli** [comment]
Implementing such a thing is incompatible with the CommandAPI's annotation system. The CommandAPI's annotation system would also require a variant (e.g. `commandapi-annotation-nbtapi`) in order to be compatible with shading both the NBTAPI and the CommandAPI at the same time.

At this point, it makes one wonder if shading is the correct thing to do here, and I'd recommend not shading because this whole package relocation thing is unnecessarily complicated and more work than it should be.

**Comment by JorelAli** [comment]
Fixed in 8.4.0.
