### ISSUE TITLE
changing permission messages

### ISSUE THREAD

**Issue by Zac694** [JorelAli/CommandAPI#247]
Have a way to change the message that is sent to the player when they're missing a permission node instead of the default.

Example:
/god
"You don't have permission to do this command"

**Comment by JorelAli** [comment]
This isn't something controllable by the CommandAPI - it uses the vanilla Minecraft permission handler which uses whatever the default error message when a player cannot run a command.

In reality, it becomes much more complicated than this, due to how clients do not actually know about commands that they don't have permission for anyway (e.g. if a player doesn't have the permission for /god, then /god won't show as gray text when typing - it'll show as red which is the standard for "this is not a valid command").

I've discussed this concept a lot on the CommandAPI discord and while this is very frequently requested, every time the answer has been "the CommandAPI can't control it".
