### ISSUE TITLE
Support for proxy servers

### ISSUE THREAD

**Issue by RedstoneWizard08** [JorelAli/CommandAPI#343]
### Description

I would love it if I were able to implement CommandAPI in my Velocity proxy server, since it would make the experience on my server network so much better. I believe that Velocity uses the bridgadier API, so theoretically the idea should be fairly easy to implement.

### Expected code

N/A

### Extra details

N/A

**Comment by JorelAli** [comment]
Theoretically it's easy to implement but realistically it's a massive undertaking that requires effectively rewriting the everything.

This is because every part of the CommandAPI (it's frontend and backend) is all tailored for the Bukkit API. Everything would have to be rewritten to support velocity command senders and at the moment current development is being focussed on improving the main Bukkit implementation.

There have been attempts using generics (which ended up blowing up into classes with ~18 generic types) and I haven't had the time to dedicate to doing this yet.

Another key factor is the whole idea of what "adding velocity support" even means. I've never used velocity, I don't know if registering a command on the proxy server is expected to trickle down to other servers that connect to velocity, I don't know how minecraft-specific arguments (e.g. location arguments) would work for players when that information may not be accessible. So on top of the whole rewriting everything, there's also a whole "gotta learn how everything works all from scratch" as well!

**Comment by RedstoneWizard08** [comment]
@JorelAli If you want to check out some code for what I've done with velocity, here's a link: https://github.com/nosadnile/flow
What I know about velocity is that commands are registered at runtime, and instead of using the Bukkit API's wrapper of the Adventure API, it uses the Adventure API directly, meaning chat colors and formatting are a little more complicated, but there are workarounds for that. When I have time, I can try to help retrofit CommandAPI to work with velocity, if you want.

**Comment by JorelAli** [comment]
You're more than welcome to try to retrofit the CommandAPI for velocity!

My past attempts can be found in [dev/velocity](https://github.com/JorelAli/CommandAPI/tree/dev/velocity) and [dev/velocity-attempt-2](https://github.com/JorelAli/CommandAPI/tree/dev/velocity-attempt-2)

**Comment by RedstoneWizard08** [comment]
All right! Thanks!

**Comment by RedstoneWizard08** [comment]
By the way, here's my plan:
- Try to isolate the classes of CommandAPI's core into generic classes only requiring bridgadier.
- Create compatibility layers to allow auto-registering, datapack support, and other features for each API. I will try to isolate as much of this as possible into a core API package for reduced code duplication.
- Request review on the PR.

Also, @JorelAli, is it okay if I use gradle for my PR? It might change the structure a bit, but I can't deal with maven, since I hate XML, because for me it is clunky, overcomplicated, and overly verbose. Maven also gets in the way of my ADHD because of that.

**Comment by JorelAli** [comment]
Feel free to use gradle for your PR - you do you! I've basically been at a bit of a loss with trying to add velocity support, so I'm all for some fresh ideas from someone that knows velocity more than I do.

If your PR is able to successfully achieve these outcomes, I'm more than willing to accept it and convert it back to maven myself, don't worry :)

**Comment by RedstoneWizard08** [comment]
All right. Thanks!

**Comment by JorelAli** [comment]
For all intents and purposes, this has been implemented in SNAPSHOT builds. We now have some support for Velocity which can be accessed via the snapshot repo, and we have some documentation for this [on the live dev documentation](https://commandapi-live-docs.jorel.dev/velocity_intro.html).

While Velocity will be fully released in 10.0.0, I'm happy to say Velocity is in a "usable" state now and can warrant closing this as implemented.

**Comment by RedstoneWizard08** [comment]
Yay!
