### ISSUE TITLE
GreedyStringArgument does not update on replaceSuggestions()

### ISSUE THREAD

**Issue by HoshiKurama** [JorelAli/CommandAPI#449]
### CommandAPI version

9.0.1

### Minecraft version

1.19.3

### Are you shading the CommandAPI?

Yes

### What I did

The code below triggers the issue:
```kotlin
commandAPICommand("buggedCommand") {
    argument(GreedyStringArgument("constraints")) {
        replaceSuggestions(ArgumentSuggestions.stringCollection { args ->
            val currentLength = args.currentArg.length.toString()
            println(currentLength)
            return@stringCollection listOf(currentLength)
        })
    }
    executes(CommandExecutor { _, _ ->  })
    register()
}
```
Type /buggedCommand

### What actually happened

 Only 0 shows up when size = 0. Still prints in console and thus sending to the replacer.
[Gyazo Link to console and game](https://gyazo.com/5953dbbfd4b0317bd948d923e4c0417f)

### What should have happened

Receive a tab completion for the current string size and print the value into console.

### Server logs and CommandAPI config

Shaded and Vanilla

**Comment by DerEchtePilz** [comment]
Well, this is just not how suggestions work. 
As you can clearly see yourself you receive a suggestion when the cursor is at position zero. That's the exact position the `com.mojang.brigadier.suggestion.SuggestionsBuilder` places the suggestion for the current argument.
Because the builder isn't moved to any position after position zero you don't receive suggestion after position zero.
This is working as intended.

On a different note, I also want to give suggestions/improvements for your code.
1. The Kotlin DSL doesn't require you to add the register, it does that automatically
2. You should use the executor methods the DSL provides. More about them [here](https://commandapi.jorel.dev/9.0.1/kotlindsl.html#executors). If you use them, you don't need to specify the `CommandExecutor` class
3. You don't need to use the `argument()` method to add an argument. The Kotlin DSL implements almost every argument as a method itself. The `argument()` method mainly was added to provide a way of implementing arguments that use a builder (for example: `MapArgument`, `ListArgument`, `ListTextArgument`, `CustomArgument`)

**Comment by willkroboth** [comment]
> Edit: I found [this](https://commandapi.jorel.dev/9.0.0/brigadiersuggestions.html?highlight=SuggestionsBuilder#brigadier-suggestions)

Ah yes, brigadier suggestions should help. The [`CommandArgument`](https://github.com/JorelAli/CommandAPI/blob/master/commandapi-platforms/commandapi-bukkit/commandapi-bukkit-core/src/main/java/dev/jorel/commandapi/arguments/CommandArgument.java), [`ListArgument`](https://github.com/JorelAli/CommandAPI/blob/master/commandapi-platforms/commandapi-bukkit/commandapi-bukkit-core/src/main/java/dev/jorel/commandapi/arguments/ListArgument.java), and [`MapArgument`](https://github.com/JorelAli/CommandAPI/blob/master/commandapi-platforms/commandapi-bukkit/commandapi-bukkit-core/src/main/java/dev/jorel/commandapi/arguments/MapArgument.java) are examples of arguments in the CommandAPI that use brigadier suggestions. Those could help give an idea of how to approach something like that. Since you'll be using the brigadier `SuggestionsBuilder` class, you could also take a look at this [documentation](https://commandapi.jorel.dev/javadocs/html/classcom_1_1mojang_1_1brigadier_1_1suggestion_1_1_suggestions_builder.html), which details all of those methods.

**Comment by HoshiKurama** [comment]
Just an update, creating and offset at the link above solved my problem.
